[[constraint]]
  name = "github.com/Financial-Times/go-fthealth"
  version = "0.4.0"

[[constraint]]
  name = "github.com/Financial-Times/neo-utils-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/Financial-Times/service-status-go"
  version = "0.1.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.4.0"

[[constraint]]
  name = "github.com/jawher/mow.cli"
  version = "1.0.1"

[[constraint]]
  name = "github.com/jmcvetta/neoism"
  source = "github.com/Financial-Times/neoism"
  version = "^2.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  revision = "4e9e7f972a5d33e1fe6fc615eb9abe0d40de4bf7"
  name = "github.com/Financial-Times/go-logger"

[[constraint]]
  revision = "f1cd95aa58cc18aabf1e0d18a31c9091efe15367"
  name = "github.com/Financial-Times/upp-micro-kit"
