name    'ft-public_annotations_api'
version '0.0.0'
source 'git@github.com:Financial-Times/public-annotations-api.git'
author 'ft'
license 'Apache License, Version 2.0'
summary 'Provides a public API for users to lookup annotations for a specific piece of content'
description 'Public API for retrieving annotations for a specific piece of content'
project_page 'https://github.com/Financial-Times/public-annotations-api'

## Add dependencies, if any:
dependency 'ft/go_service_profile', '>= 0.0.0'
